runs:
  using: composite
  steps:
    - name: "Install UV"
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
    
    - name: "Install Just"
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y just

    - name: "Install dependencies for C++ index builder and package"
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libstemmer-dev build-essential git clang-format
